feature-22401
ArrowSphere/public-api-client pull request #110
Opened 2023-01-04 17:07 UTC by djseif19

2023-01-05 09:34 UTC, myst6re commented on src/Billing/Entities/ErpExportType.php
> +        $this->name= $data[self::COLUMN_NAME];
```suggestion
        $this->name = $data[self::COLUMN_NAME];
```

2023-01-05 09:35 UTC, jeromearz commented on src/Billing/Entities/ErpExportType.php
> +        $this->name= $data[self::COLUMN_NAME];
```suggestion
        $this->name = $data[self::COLUMN_NAME];
```

2023-01-05 09:35 UTC, jeromearz commented on src/Billing/Entities/ErpExportType.php
> +        $this->columns= $data[self::COLUMN_COLUMNS];
```suggestion
        $this->columns = $data[self::COLUMN_COLUMNS];
```

2023-01-05 09:35 UTC, jeromearz commented on src/Billing/ErpExportsClient.php
> +    public const EXPORT_FILTERS_DATE_FROM= 'from';
```suggestion
    public const EXPORT_FILTERS_DATE_FROM = 'from';
```

2023-01-05 09:35 UTC, jeromearz commented on src/Billing/ErpExportsClient.php
> +    public const EXPORT_FILTERS_DATE_TO= 'to';
```suggestion
    public const EXPORT_FILTERS_DATE_TO = 'to';
```

2023-01-05 16:10 UTC, jeromearz commented on doc/erp-exports.md
> +| columns.           | `array`                | ['column-reference1' => 'Friendly Name','column-reference2' => 'Vendor Name',] | list of columns to export                          |
```suggestion
| columns           | `array`                | ['column-reference1' => 'Friendly Name','column-reference2' => 'Vendor Name'] | list of columns to export                          |
```

2023-01-05 16:10 UTC, jeromearz commented on doc/erp-exports.md
> +    echo "column-reference: {$key} => friendly-name: {$value} ";
```suggestion
    echo "column-reference: {$key} => friendly-name: {$value}\n";
```

2023-01-10 10:50 UTC, jeromearz approved these changes

2023-02-15 16:23 UTC, pfeyssaguet requested changes

2023-02-15 16:23 UTC, pfeyssaguet commented on src/Billing/ErpExportsClient.php
> +            $result = $data['data']['columns'];
you're supposed to create an entity object here, instead of returning an array containing we don't know what

2023-02-15 16:23 UTC, pfeyssaguet commented on src/Billing/ErpExportsClient.php
> +            $result = $data['data']['exportTypes'];
same here: you're using the response without reprocessing into an object so we won't have any autocompletion and won't know what fields are inside the response

2023-02-15 16:23 UTC, pfeyssaguet commented on src/Billing/ErpExportsClient.php
> +            $result = new ErpExportType($data['data']);
here you did it right

2023-02-15 16:23 UTC, pfeyssaguet commented on src/Billing/Enum/RateTypeEnum.php
> +     * @var null none index
```suggestion
     * @var string none index
```

2023-02-15 16:23 UTC, pfeyssaguet commented on src/Billing/StatementsClient.php
> +     * @var integer per page default value
```suggestion
     * @var int per page default value
```
integer ain't a valid PHP type

2023-02-15 16:23 UTC, pfeyssaguet commented on CHANGELOG.md
> +- Add a new client for billing erp export, its Entities and its tests.
```suggestion
- Add a new client `ErpExportsClient` for billing ERP export, its entities and its tests.
```

2023-02-15 16:23 UTC, pfeyssaguet commented on doc/billing-preferences.md
> +This client will gives a uniform access to see and edit your preferences and retrieve your custom billing statements.
```suggestion
This client will give an uniform access to see and edit your preferences and retrieve your custom billing statements.
```

2023-02-15 16:23 UTC, pfeyssaguet commented on doc/billing-preferences.md
> +custom billing statements with custom headers. for more information about billing statements [click here](billing-statements.md).
```suggestion
custom billing statements with custom headers. For more information about billing statements [click here](billing-statements.md).
```

2023-02-15 16:23 UTC, pfeyssaguet commented on doc/billing-statements.md
> +Billing statements are the documents issued prior to the issue of the local Invoice.
```suggestion
Billing statements are the documents issued prior to the issue of the local invoice.
```

2023-02-15 16:23 UTC, pfeyssaguet commented on doc/billing-statements.md
> +This client gives a uniform access to all the billing information before their transformation
```suggestion
This client gives an uniform access to all the billing information before their transformation 
```

2023-02-15 16:23 UTC, pfeyssaguet commented on doc/billing-statements.md
> +into the invoice that'll fit the local country's legislation.
```suggestion
into the invoice that will fit the local country's legislation.
```

2023-02-15 16:23 UTC, pfeyssaguet commented on doc/billing-statements.md
> +Billing statements & their lines are technically referenced by their "reference" field,
```suggestion
Billing statements and their lines are technically referenced by their `reference` field,
```

2023-02-15 17:12 UTC, pfeyssaguet approved these changes

2023-02-16 09:41 UTC, myst6re approved these changes

2023-02-16 09:42 UTC, jeromearz approved these changes

2023-02-16 10:14 UTC, merged