Feature/are 13984 add description column
ArrowSphere/public-api-client pull request #66
Opened 2021-09-16 13:47 UTC by MathRak

2021-09-16 16:13 UTC, A84126 approved these changes

2021-09-16 16:14 UTC, A84126 requested changes
You need to rebase apparently

2021-09-16 17:36 UTC, A84126 approved these changes

2021-09-17 08:56 UTC, pfeyssaguet requested changes
Please update the changelog

2021-09-17 13:06 UTC, merged